# metallb-configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb-config
data:
  config: |
    address-pools:
    - name: public-ips
      protocol: layer2
      addresses:
      - ${PUBLIC_IP}/32
