# mongodb-deploy.yaml

# Persistent Volume Claim for MongoDB data (Unchanged)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
# MongoDB Service to expose the database (Unchanged)
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
# ConfigMap with a single JavaScript init script
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-cm
data:
  # This script now only focuses on the application user
  init-mongo.js: |
    db = db.getSiblingDB('admin');
    print('Creating application user from environment variables...');
    db.createUser({
      user: process.env.MONGODB_APP_USER,
      pwd: process.env.MONGODB_APP_PASSWORD,
      roles: [
        { role: "enableSharding", db: "admin" },
        { role: "readWrite", db: "wyd" }
      ]
    });
    print("Switching to 'wyd' database and creating it.");
    db = db.getSiblingDB('wyd');
    db.createCollection('init_collection');
    print('✅ MongoDB initialization complete.');
---
# MongoDB Deployment without an initContainer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            # These are for the MongoDB server to establish the first root user.
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wyd-credentials
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wyd-credentials
                  key: MONGO_INITDB_ROOT_PASSWORD
            # These are for the custom init script to create the application user.
            - name: MONGODB_APP_USER
              valueFrom:
                secretKeyRef:
                  name: wyd-credentials
                  key: MONGODB_APP_USER
            - name: MONGODB_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wyd-credentials
                  key: MONGODB_APP_PASSWORD
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongo-init-config-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - name: mongo-init-config-volume
          configMap:
            name: mongo-init-cm