#rest-server-deploy.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-server
  template:
    metadata:
      labels:
        app: rest-server
    spec:
      containers:
        - name: rest-server-container
          image: redduality/wyd-rest-server:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://+:80
            # Authentication
            - name: AUTHENTICATION_ISSUER_URL
              valueFrom:
                configMapKeyRef:
                  name: rest-server-config
                  key: AUTHENTICATION_ISSUER_URL
            - name: AUTHENTICATION_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: rest-server-config
                  key: AUTHENTICATION_AUDIENCE
            # Notification credentials
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: wyd-credentials
                  key: GOOGLE_APPLICATION_CREDENTIALS
            # MongoDB
            - name: MONGODB_HOSTNAME
              value: mongodb-service
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: rest-server-config
                  key: DATABASE_NAME
            - name: MONGODB_APP_USER
              valueFrom:
                secretKeyRef:
                  name: wyd-credentials
                  key: MONGODB_APP_USER
            - name: MONGODB_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wyd-credentials
                  key: MONGODB_APP_PASSWORD
            # MinIO
            - name: OBJ_STORAGE_ENDPOINT
              value: "http://minio:9000"
            - name: OBJ_STORAGE_PUBLIC_ENDPOINT
              value: "https://blobs.${DOMAIN_NAME}"  
            - name: OBJ_STORAGE_USER
              valueFrom:
                secretKeyRef:
                  name: wyd-credentials
                  key: OBJ_STORAGE_USER
            - name: OBJ_STORAGE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wyd-credentials
                  key: OBJ_STORAGE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: rest-server-service
spec:
  selector:
    app: rest-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
